export const MESSAGES = {
	unknowError: 'Đã xảy ra lỗi. Vui lòng thử lại sau',
	usernameExisted: 'Tài khoản đã tồn tại',
	passwordNotMatched: 'Mật khẩu không hợp lệ',
	usernameNotFound: 'Tài khoản không tồn tại',
	registerSuccessfully: 'Đăng ký thành công',
	loginSucessfully: 'Đăng nhập thành công',
	refreshTokenNotFound: 'Không tìm thấy Refresh Token. Vui lòng đăng nhập lại',
	accessTokenNotFound: 'Không tìm thấy Access Token. Vui lòng đăng nhập lại',
	logoutSuccessfully: 'Đăng xuất thành công',
	userNotFound: 'Không tìm thấy thông tin người dùng',
	startANewMessage: 'Hãy bắt đầu cuộc trò chuyện',
	updatePasswordSuccessfully: 'Cập nhật mật khẩu thành công',
	addFriendNotificationNotFound: 'Không tìm thấy yêu cầu kết bạn',
	addFriendNotificationDeleted: 'Yêu cầu kết bạn đã xóa',
	addFriendNotificationSenderCannotAccept: 'Người gửi không thể chấp nhật yêu cầu kết bạn',
	cannotDeclineADeclinedAddFriendNotification: 'Không thể xóa yêu cầu kết bạn đã bị xóa',
	addFriendSuccessfully: 'Thêm bạn bè thành công',
};
