export const VIDEO_SOCKET_EVENT = {
	CALL_USER: 'CALL_USER',
	END_CALL: 'END_CALL',
	RECEIVED_END_CALL: 'RECEIVED_END_CALL',
	ANSWER_CALL: 'ANSWER_CALL',
	CALL_ACCEPTED: 'CALL_ACCEPTED',
	RECEIVED_CALL: 'RECEIVED_CALL',
	SEND_VIDEO_CALL_RECEIVER_ID: 'SEND_VIDEO_CALL_RECEIVER_ID',
	RECEIVE_VIDEO_CALL_RECEIVER_ID: 'RECEIVE_VIDEO_CALL_RECEIVER_ID',
	SEND_CALLER_DETAIL: 'SEND_CALLER_DETAIL',
};
