export const SOCKET_CONSTANT = {
	NEW_USER: 'NEW_USER',

	SEND_ADD_FRIEND_NOTIFICATION: 'SEND_ADD_FRIEND_NOTIFICATION',
	SEND_ACCEPTED_ADD_FRIEND_NOTIFICATION: 'SEND_ACCEPTED_ADD_FRIEND_NOTIFICATION',

	RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',

	CALL_USER: 'CALL_USER',
	END_CALL: 'END_CALL',
	ANSWER_CALL: 'ANSWER_CALL',
	CALL_ACCEPTED: 'CALL_ACCEPTED',
	SEND_VIDEO_CALL_RECEIVER_ID: 'SEND_VIDEO_CALL_RECEIVER_ID',
	RECEIVE_VIDEO_CALL_RECEIVER_ID: 'RECEIVE_VIDEO_CALL_RECEIVER_ID',
	SEND_CALLER_DETAIL: 'SEND_CALLER_DETAIL',
	RECEIVED_CALL: 'RECEIVED_CALL',
};
